### ISSUE TITLE
Collision with The Events Calendar PRO

### ISSUE THREAD

**Issue by SirLouen** [michaelbourne/Custom-Icons-for-Elementor#1]
I've found that in the file
custom-icons-for-elementor/includes/save.font.php
line 24

There is a collision with The Events Calendar (pro)

`PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'SaveFont_ECIcons' does not have a method 'tribe_geosearch' in /var/www/site/wp-includes/class-wp-hook.php on line 286`

I think that the problem is that in line 21 it asks for "action" in a similar way as The Events Calendar

Code in The Events Pro:
events-calendar-pro/src/resources/js/tribe-events-pro.js
ts.url_params['action'] = 'tribe_geosearch';

I think this can be solved by modifying the "action" parameter to eci_action in includes/save.font.php and assets/js/elementor-custom-icons.js

**Comment by michaelbourne** [comment]
That's a good catch, and a good suggestion. I pushed another update with your changes implemented.

Greatly appreciated.

[edit: I also pushed my preliminary update for E2.6+ prior to seeing this, so I skipped the PR you had.]
